services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - FRONTEND_URL=http://localhost:3000
    # volumes:
    #   - ./Backend:/app/data  # Commented out for now

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

